GET http://localhost:3001/lists


###
GET http://localhost:3001/archived-lists


###
POST http://localhost:3001/list/new
content-type: application/json

{
  "listName": "Encore une liste"
}

###
DELETE http://localhost:3001/list/delete/6261352ed668c7769aa38dab


###
GET http://localhost:3001/list/archive/625e863423c327f94b42a0b6

###
PUT http://localhost:3001/list/update/625e863423c327f94b42a0b7
content-type: application/json

{
  "listName": "Nouveau nom à la liste 2"
}


###
PUT http://localhost:3001/list/6262a94b40258ec72c563cc1/addtask
content-type: application/json

{
  "taskName": "Nouvelle tâche"
}

###
PUT http://localhost:3001/list/6262a94b40258ec72c563cc1/delete/626962ad122e31955d0c0857
